#!/bin/bash 
 function disable_bt {
            echo "Disabling Bluetooth"
            if grep -q pi3-disable-bt "/boot/config.txt"; then
                echo 'Bluetooth Disabled'
            else
            echo 'dtoverlay=pi3-disable-bt' | sudo tee -a /boot/config.txt
                echo 'Bluetooth Disabled'
            fi
            sudo systemctl disable hciuart
           }


echo "PISKY_Pure - Installation"
echo "-------------------------"
sleep 1

echo -e "\nSetting up serial ports..."
sudo systemctl mask serial-getty@ttyAMA0.service
sudo sed -e "s/console=serial0,115200//g" -i.backup /boot/cmdline.txt

echo -e "\nOneWire enabled"
sudo raspi-config nonint do_onewire 0

rev=$(cat /proc/cpuinfo|grep Revision|awk -F: '$0=$2'|tr -d ' ' )

case "$rev" in
        a02082)
            disable_bt
            ;;
        a22082)
            disable_bt
            ;;
        9000c1)
            sudo systemctl disable bluetooth.service
            ;;
        *)
            echo "No bluetooth to disable"
            ;;
esac

echo -e "\nCamera support is enabled"
sudo raspi-config nonint do_camera 0

echo -e "\nLora transmisssion is enabled"
sudo raspi-config nonint do_spi 0

echo -e "\nI2C is enabled"
sudo raspi-config nonint do_i2c 0

echo -e "\nInstalling PiGPIO"
echo      "-----------------"
cd
sudo apt install python-setuptools python3-setuptools
wget https://github.com/HB9GAA/PIGPIO/archive/master.zip
unzip master.zip
cd PIGPIO-master
make
sudo make install

echo -e "\nInstalling Wiring Pi"
echo      "--------------------"
sudo apt-get install wiringpi

echo -e "\nInstalling SSDV"
echo      "---------------"
sudo apt-get install ssdv
cd

echo -e "\nInstalling PISKY_Pure Firmware"
echo      "---------------------------------"
cd ~/PISKY_Pure
./build
cd ~/PISKY_Pure/tracker

read -rp $'\n\nDo you want to edit your CALL in the file pisky.txt? [Y,n]' choice 
case $choice in  
  n|N) ;;
  *) 
      sudo nano /boot/pisky.txt;; 
esac
