#!/bin/bash 
 function disable_bt {
            echo "Detected Raspberry Pi 3...Disabling Bluetooth"
            if grep -q pi3-disable-bt "/boot/config.txt"; then
                echo 'Bluetooth Disabled'
            else
            echo 'dtoverlay=pi3-disable-bt' | sudo tee -a /boot/config.txt
                echo 'Bluetooth Disabled'
            fi
            sudo systemctl disable hciuart
           }


echo "PISKY_Pure - Installation"
echo "-------------------------"
sleep 1

echo -e "\n\nSetting up serial ports..."
sleep 1
sudo systemctl mask serial-getty@ttyAMA0.service
sudo sed -e "s/console=serial0,115200//g" -i.backup /boot/cmdline.txt

echo -e "\n\nEnabling OneWire support..."
sleep 1
sudo raspi-config nonint do_onewire 0 #Default

rev=$(cat /proc/cpuinfo|grep Revision|awk -F: '$0=$2'|tr -d ' ' )

case "$rev" in
        a02082)
            disable_bt
            ;;
        a22082)
            disable_bt
            ;;
        *)
            echo "No bluetooth to disable"
            ;;
esac

echo -e "\n Camera support is enabled"
sleep 1
sudo raspi-config nonint do_onewire 0 #Default

echo -e "\nLora transmisssion is enabled"
sleep 1
sudo raspi-config nonint do_spi 0 #Default

echo -e "\nI2C is enabled"
sleep 1
sudo raspi-config nonint do_i2c 0 #Default

read -rp $'\nAre you using a USB Webcam[y,N]' choice 
case $choice in  
  n|N) ;;
  *) 
      echo "Installing fswebcam"
      echo "-------------------"
      sleep 1
      sudo apt-get install fswebcam ;; 
esac

echo -e "\nInstalling PiGPIO"
echo      "-----------------"
sleep 1
cd
wget abyz.me.uk/rpi/pigpio/pigpio.zip
unzip pigpio.zip
cd PIGPIO
make
sudo make install

echo -e "\nInstalling Wiring Pi"
echo      "--------------------"
sleep 1
sudo apt-get install wiringpi

echo -e "\nInstalling SSDV"
echo      "---------------"
sleep 1
sudo apt-get install ssdv
cd

echo -e "\nInstalling Pi in the Sky Software"
echo      "---------------------------------"
sleep 1
cd ~/PISKY_Pure
./build
cd ~/PISKY_Pure/tracker

read -rp $'\n\nDo you want to edit your CALL in the file pisky.txt? [Y,n]' choice 
case $choice in  
  n|N) ;;
  *) 
      echo "Open the file pisky.txt"
      echo "-----------------------"
      sleep 1
      sudo nano /boot/pisky.txt;; 
esac
